# Generated by Django 4.2.5 on 2023-09-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
