# Generated by Django 4.2.5 on 2023-09-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personres', '0002_remove_person_age_remove_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
