# Generated by Django 4.2.5 on 2023-09-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personres', '0003_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
