# Generated by Django 4.2.5 on 2023-09-11 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personres', '0004_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name can only contain letters and spaces.', regex='^[A-Za-z\\s]*$')]),
        ),
    ]
